#!/bin/bash

register_project_for_upgrade manila
register_db_to_save manila

export BASE_RUN_SMOKE=False
export TARGET_RUN_SMOKE=False

# NOTE(vponomaryov): stable client is used for keeping scenarios stable
# so they are not broken by changed CLI views.
devstack_localrc base MANILACLIENT_BRANCH="stable/ussuri"
devstack_localrc target MANILACLIENT_BRANCH="stable/ussuri"

devstack_localrc target MANILA_USE_DOWNGRADE_MIGRATIONS=False
