#!/bin/bash

register_project_for_upgrade manila
register_db_to_save manila

export BASE_RUN_SMOKE=False
export TARGET_RUN_SMOKE=False
export ENABLE_TEMPEST=False

devstack_localrc base enable_service manila m-api m-shr m-sch m-dat
devstack_localrc base enable_plugin manila git://git.openstack.org/openstack/manila stable/pike
devstack_localrc base MANILA_UI_ENABLED=False
devstack_localrc base OSLO_SERVICE_WORKS=True

# NOTE(vponomaryov): stable client is used for keeping scenarios stable
# so they are not broken by changed CLI view.
devstack_localrc base MANILACLIENT_BRANCH="stable/pike"

devstack_localrc target enable_service manila m-api m-shr m-sch m-dat
devstack_localrc target enable_plugin manila git://git.openstack.org/openstack/manila
devstack_localrc target MANILA_UI_ENABLED=False
devstack_localrc target OSLO_SERVICE_WORKS=True
devstack_localrc target MANILA_USE_DOWNGRADE_MIGRATIONS=False
devstack_localrc target MANILACLIENT_BRANCH="stable/pike"
