- project:
    templates:
      - publish-openstack-docs-pti
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-wallaby-jobs
      - check-requirements
      - release-notes-jobs-python3
      - periodic-stable-jobs
    check:
      jobs:
        - manila-tox-genconfig
        - openstack-tox-pylint:
            voting: false
            timeout: 5400
        - openstack-tox-cover:
            voting: false
        - manila-tempest-plugin-dummy-no-dhss
        - manila-tempest-plugin-dummy-dhss
        - manila-tempest-plugin-lvm
        - manila-tempest-plugin-cephfs-native:
            voting: false
        - manila-tempest-plugin-cephfs-nfs:
            voting: false
        - manila-tempest-plugin-container:
            voting: false
        - manila-tempest-plugin-generic:
            voting: false
        - manila-tempest-plugin-glusterfs-native:
            voting: false
        - manila-tempest-plugin-glusterfs-nfs:
            voting: false
        - manila-tempest-plugin-zfsonlinux:
            voting: false
        - manila-grenade:
            voting: false
        - manila-rally-no-ss:
            voting: false
        - manila-rally-ss:
            voting: false
    gate:
      queue: manila
      jobs:
        - manila-tempest-plugin-dummy-no-dhss
        - manila-tempest-plugin-dummy-dhss
        - manila-tempest-plugin-lvm
    experimental:
      jobs:
        - tripleo-ci-centos-8-scenario004-standalone

- job:
    name: manila-tox-genconfig
    parent: openstack-tox
    description: |
      Run tests for manila project.

      Uses tox with the ``genconfig`` environment.
    post-run: playbooks/manila-tox-genconfig/post.yaml
    vars:
      tox_envlist: genconfig

- job:
    name: manila-rally-no-ss
    parent: rally-task-manila-no-ss
    irrelevant-files: &irrelevant-files
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^manila/tests/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$
    vars:
      rally_task: rally-jobs/rally-manila-no-ss.yaml
      devstack_plugins:
        rally-openstack: https://opendev.org/openstack/rally-openstack
    required-projects:
      - openstack/rally-openstack

- job:
    name: manila-rally-ss
    parent: rally-task-manila-ss
    irrelevant-files: *irrelevant-files
    vars:
      rally_task: rally-jobs/rally-manila.yaml
      devstack_plugins:
        rally-openstack: https://opendev.org/openstack/rally-openstack
    required-projects:
      - openstack/rally-openstack
